spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: app-database
      username: app-user
      password: app-user-pwd
#      authentication-database: admin
      auto-index-creation: true

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

logging:
  level:
    root: INFO

application:
  initializeDatabase: false # clear database and load from CSV
