spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: app-database
      username: app-user
      password: app-user-pwd
      auto-index-creation: true
#      authentication is done directly in app-database
#      authentication-database: admin
#      mongosh mongo --host localhost --port 27017 -u app-user -p --authenticationDatabase app-database

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

logging:
  level:
    root: INFO

application:
  initializeDatabase: false # clear database and load from CSV
